esphome:
  name: bms
  friendly_name: bms

esp32:
  board: esp32dev
  framework:
    type: arduino

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "0Sn0wgXKEwOjMs+RkyTEYg9w9D/+4kHGzUqM1EsdT+0="

ota:
  platform: esphome
  password: "f6cee402ca670c47e4d937fadc0661c8"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

external_components:
  - source:
      type: git
      url: https://github.com/dansck/esphome-pace-bms
      ref: main
    components: [pace_bms]
    refresh: "10s"

uart:
  - id: uart_bus
    tx_pin: GPIO1
    rx_pin: GPIO3
    baud_rate: 9600 # Setting matching BAUD_RATE from Python script
  - id: uart_bus2
    tx_pin: GPIO17
    rx_pin: GPIO16
    baud_rate: 9600 # Setting matching BAUD_RATE from Python script

pace_bms:
  id: ufo_bms
  uart_id: uart_bus2
  
sensor:
  - platform: pace_bms
    voltage:
      name: "BMS Voltage"
    current:
      name: "BMS Current"
    remaining_capacity:
      name: "Remaining Capacity"
    nominal_capacity:
      name: "Nominal Capacity"
    full_capacity:
      name: "Full Capacity"
    cycles:
      name: "Cycles"
    state_of_health:
      name: "State of Health"
    state_of_charge:
      name: "State of Charge"
    cell_max_volt_diff:
      name: "Max Voltage Difference"
    charge_fet:
      name: "Charge FET"
    discharge_fet:
      name: "Discharge FET"
    ac_in:
      name: "AC In"
    current_limit:
      name: "Current Limit"
    heart:
      name: "Heart"
    pack_indicate:
      name: "Pack Indicate"
    protection_discharge_current:
      name: "Protection Discharge Current"
    protection_charge_current:
      name: "Protection Charge Current"
    protection_short_circuit:
      name: "Protection Short Circuit"
    reverse:
      name: "Reverse"
    temperature:
      name: "BMS Temperature"
    cell_voltages:
      - name: "Pack 1 Cell 1 Voltage"
      - name: "Pack 1 Cell 2 Voltage"
      - name: "Pack 1 Cell 3 Voltage"
      - name: "Pack 1 Cell 4 Voltage"
      - name: "Pack 1 Cell 5 Voltage"
      - name: "Pack 1 Cell 6 Voltage"
      - name: "Pack 1 Cell 7 Voltage"
      - name: "Pack 1 Cell 8 Voltage"
      - name: "Pack 1 Cell 9 Voltage"
      - name: "Pack 1 Cell 10 Voltage"
      - name: "Pack 1 Cell 11 Voltage"
      - name: "Pack 1 Cell 12 Voltage"
      - name: "Pack 1 Cell 13 Voltage"
      - name: "Pack 1 Cell 14 Voltage"
      - name: "Pack 1 Cell 15 Voltage"
    temperatures:
      - name: "Pack 1 Temperature 1"
      - name: "Pack 1 Temperature 2"
      - name: "Pack 1 Temperature 3"
      - name: "Pack 1 Temperature 4"
      - name: "Pack 1 Temperature 5"
      - name: "Pack 1 Temperature 6"
    balancing_1:
      name: "Pack 1 Balancing 1"
    balancing_2:
      name: "Pack 1 Balancing 2"
    warnings:
      name: "Pack 1 Warnings"
    design_capacity:
      name: "Pack Design Capacity"
    pack_full_capacity:
      name: "Pack Full Capacity"
    pack_remaining_capacity:
      name: "Pack Remaining Capacity"
    pack_state_of_health:
      name: "Pack State of Health"
    pack_state_of_charge:
      name: "Pack State of Charge"
