esphome:
  name: bms
  friendly_name: bms

esp32:
  board: esp32dev
  framework:
    type: arduino

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "0Sn0wgXKEwOjMs+RkyTEYg9w9D/+4kHGzUqM1EsdT+0="

ota:
  platform: esphome
  password: "f6cee402ca670c47e4d937fadc0661c8"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

external_components:
  - source:
      type: git
      url: file:///Users/ds/src/esphome-pace-bms/
      ref: dev1
    components: [pace_bms]
    refresh: "10s"

uart:
  - id: uart_bus
    tx_pin: GPIO1
    rx_pin: GPIO3
    baud_rate: 9600 # Setting matching BAUD_RATE from Python script
  - id: uart_bus2
    tx_pin: GPIO17
    rx_pin: GPIO16
    baud_rate: 9600 # Setting matching BAUD_RATE from Python script

pace_bms:
  id: ufo_bms
  uart_id: uart_bus2
  
sensor:
  - platform: pace_bms
    voltage:
      name: "BMS Voltage"
    current:
      name: "BMS Current"
    remaining_capacity:
      name: "BMS Remaining Capacity"
    nominal_capacity:
      name: "BMS Nominal Capacity"
    full_capacity:
      name: "BMS Full Capacity"
    cycles:
      name: "BMS Cycles"
    state_of_health:
      name: "BMS State of Health"
    state_of_charge:
      name: "BMS State of Charge"
    cell_max_volt_diff:
      name: "BMS Cell Max Voltage Difference"
    charge_fet:
      name: "BMS Charge FET"
    discharge_fet:
      name: "BMS Discharge FET"
    ac_in:
      name: "BMS AC In"
    current_limit:
      name: "BMS Current Limit"
    heart:
      name: "BMS Heart"
    pack_indicate:
      name: "BMS Pack Indicate"
    protection_discharge_current:
      name: "BMS Protection Discharge Current"
    protection_charge_current:
      name: "BMS Protection Charge Current"
    protection_short_circuit:
      name: "BMS Protection Short Circuit"
    reverse:
      name: "BMS Reverse"
    temperature:
      name: "BMS Temperature"

    cell_voltages:
      - name: "Pack 1 Cell 1 Voltage"
      - name: "Pack 1 Cell 2 Voltage"
      - name: "Pack 1 Cell 3 Voltage"
      - name: "Pack 1 Cell 4 Voltage"
      - name: "Pack 1 Cell 5 Voltage"
      - name: "Pack 1 Cell 6 Voltage"
      - name: "Pack 1 Cell 7 Voltage"
      - name: "Pack 1 Cell 8 Voltage"
      - name: "Pack 1 Cell 9 Voltage"
      - name: "Pack 1 Cell 10 Voltage"
      - name: "Pack 1 Cell 11 Voltage"
      - name: "Pack 1 Cell 12 Voltage"
      - name: "Pack 1 Cell 13 Voltage"
      - name: "Pack 1 Cell 14 Voltage"
      - name: "Pack 1 Cell 15 Voltage"
    temperatures:
      - name: "Pack 1 Temperature 1"
      - name: "Pack 1 Temperature 2"
      - name: "Pack 1 Temperature 3"
      - name: "Pack 1 Temperature 4"
      - name: "Pack 1 Temperature 5"
      - name: "Pack 1 Temperature 6"
    balancing_1:
      name: "BMS Balancing 1"
    balancing_2:
      name: "BMS Balancing 2"
    warnings:
      name: "BMS Warnings"
    design_capacity:
      name: "BMS Design Capacity"
    pack_full_capacity:
      name: "BMS Pack Full Capacity"
    pack_remaining_capacity:
      name: "BMS Pack Remaining Capacity"
    pack_state_of_health:
      name: "BMS Pack State of Health"
    pack_state_of_charge:
      name: "BMS Pack State of Charge"
    pack_number:
      name: "BMS Pack Number"
    pack_analog_data:
      name: "BMS Pack Analog Data"
    software_version:
      name: "BMS Software Version"
    serial_number:
      name: "BMS Serial Number"
    pack_capacity:
      name: "BMS Pack Capacity"
    warn_info:
      name: "BMS Warn Info"

